/**
 * invest-css.mjs — the one stylesheet behind both of our own pages.
 *
 * The home page's ownership block and the guide at /bali-property-investment/
 * use the same components: the same measure, the same headings, the same
 * figures, the same buttons. They used to carry two near-identical copies of
 * this CSS in two <style> blocks, which is how the two pages drifted apart.
 * Now seo-patch.mjs writes this to public/assets/css/azura-invest.css and both
 * pages link it, so a change lands on both or on neither.
 *
 * Everything here is namespaced under .azura-invest, so it cannot reach the
 * client's own Elementor sections.
 */

export const MARK = 'azura-invest';
export const CSS_PATH = 'assets/css/azura-invest.css';

/* The site header is fixed and 74px tall. Anything a link jumps to has to
   clear it, or the reader lands on a heading hidden behind the bar. */
export const HEADER_CLEARANCE = 98;

export const CSS = `/* Azura Living — the ownership block and the guide page.
   Generated by scripts/invest-css.mjs. Do not edit this file directly. */

/* --------------------------------------------------------------------------
   Shared shell
   -------------------------------------------------------------------------- */
.${MARK}{background:#FDF9EE;color:#2E2E2E;padding:96px 24px;
  font-family:"Inter","Inter Tight",system-ui,sans-serif;
  -webkit-hyphens:auto;hyphens:auto}
.${MARK}-guide{padding:112px 24px 96px}
.${MARK}-inner{max-width:760px;margin:0 auto}

.${MARK} h2,.${MARK} h3,.${MARK}-q,.${MARK}-title-anchor{
  scroll-margin-top:${HEADER_CLEARANCE}px}

.${MARK}-eyebrow{display:block;font-size:.75rem;letter-spacing:.22em;
  text-transform:uppercase;color:#CFB010;margin:0 0 18px;font-weight:600}
.${MARK} h2{font-family:"The Seasons","Lora",Georgia,serif;font-weight:400;
  font-size:clamp(1.6rem,3.4vw,2.3rem);line-height:1.22;color:#2E2E2E;
  margin:56px 0 18px;letter-spacing:-.01em}
.${MARK} h2:first-of-type{margin-top:0}
.${MARK} h3{font-family:"Inter",system-ui,sans-serif;font-weight:600;
  font-size:1.0625rem;letter-spacing:.01em;color:#2E2E2E;margin:32px 0 12px}
.${MARK} p{font-size:1.0625rem;line-height:1.72;margin:0 0 20px;color:#3A3A3A}
.${MARK} strong{font-weight:600;color:#2E2E2E}
.${MARK} a{color:#2E2E2E;text-decoration:underline;text-underline-offset:3px;
  text-decoration-color:#CFB010;text-decoration-thickness:2px}
.${MARK} a:hover{color:#000}
.${MARK} a:focus-visible,.${MARK} summary:focus-visible{
  outline:2px solid #CFB010;outline-offset:3px;border-radius:2px}

.${MARK}-figure{margin:48px 0}
.${MARK}-figure img{width:100%;height:auto;display:block;border-radius:2px}
.${MARK}-figure figcaption{font-size:.8125rem;color:#7A7466;margin-top:10px}

/* Every paragraph component names the element on purpose. The rule above sets
   the body size, colour and margin on ".azura-invest p", which is one class
   plus one element and therefore beats a class on its own — it was silently
   overriding the closing line and the legal note. */
.${MARK} p.${MARK}-close{margin:56px 0 20px;padding-top:28px;
  border-top:1px solid #E6E1D8;font-size:1.0625rem;color:#2E2E2E}
.${MARK} p.${MARK}-note{font-size:.875rem;line-height:1.6;color:#7A7466;
  margin:32px 0 0}

/* --------------------------------------------------------------------------
   Guide page head
   -------------------------------------------------------------------------- */
.${MARK}-crumbs{font-size:.8125rem;color:#7A7466;margin:0 0 28px}
.${MARK}-crumbs a{color:#7A7466;text-decoration:none}
.${MARK}-crumbs a:hover{color:#2E2E2E;text-decoration:underline}
.${MARK}-guide-h1{font-family:"The Seasons","Lora",Georgia,serif;font-weight:400;
  font-size:clamp(2rem,5vw,3.1rem);line-height:1.12;letter-spacing:-.015em;
  color:#2E2E2E;margin:0 0 22px}
.${MARK} p.${MARK}-guide-lede{font-size:1.25rem;line-height:1.6;color:#2E2E2E;
  margin:0 0 8px}

/* --------------------------------------------------------------------------
   On this page — the jump list. Twelve sections is too many to scroll blind;
   a reader who arrived on "can a foreigner buy" wants their own route.
   -------------------------------------------------------------------------- */
.${MARK}-toc{margin:44px 0 8px;padding:26px 28px;background:#F7F1E2;
  border-left:3px solid #CFB010}
.${MARK} p.${MARK}-toc-title{font-size:.75rem;letter-spacing:.2em;
  text-transform:uppercase;color:#7A7466;font-weight:600;margin:0 0 14px}
.${MARK}-toc ul{list-style:none;margin:0;padding:0;columns:2;column-gap:34px}
.${MARK}-toc li{break-inside:avoid;margin:0 0 9px;font-size:.9375rem;
  line-height:1.45}
.${MARK}-toc a{text-decoration:none;color:#3A3A3A;
  border-bottom:1px solid transparent;padding-bottom:1px}
.${MARK}-toc a:hover{color:#2E2E2E;border-bottom-color:#CFB010}

/* --------------------------------------------------------------------------
   Disclosure rows — the home page's long tail, one question per row.
   -------------------------------------------------------------------------- */
.${MARK}-q{border-top:1px solid #E6E1D8}
/* No bottom rule on the last row: the closing line below draws its own, and
   two hairlines 20px apart read as a mistake. */
.${MARK}-q:last-of-type{border-bottom:0}
.${MARK} .${MARK}-q + p.${MARK}-close{margin-top:0}
.${MARK}-q>summary{list-style:none;cursor:pointer;padding:22px 48px 22px 0;
  position:relative}
.${MARK}-q>summary::-webkit-details-marker{display:none}
.${MARK}-q>summary::after{content:"";position:absolute;right:10px;top:50%;
  width:9px;height:9px;margin-top:-8px;border-right:2px solid #CFB010;
  border-bottom:2px solid #CFB010;transform:rotate(45deg);
  transition:transform .18s ease}
.${MARK}-q[open]>summary::after{transform:rotate(-135deg);margin-top:-3px}
.${MARK}-q>summary h2{font-size:clamp(1.0625rem,1.9vw,1.3125rem);margin:0;
  line-height:1.35;display:inline-block;vertical-align:middle}
.${MARK}-q>summary:hover h2{color:#000}
.${MARK}-q-body{padding:0 0 14px}
.${MARK}-q-body>*:first-child{margin-top:0}
.${MARK}-q-body p:last-child{margin-bottom:0}
.${MARK}-q-body .${MARK}-figure{margin:28px 0 8px}
/* A row opened from a shared link should be obvious. */
.${MARK}-q:target>summary h2{color:#000}
.${MARK}-q:target{background:#F7F1E2}

/* --------------------------------------------------------------------------
   The two actions. The footer's own buttons are display:none site-wide, so
   without these the end of a 12-section page has nothing to click. Shapes and
   colours are the site's own pills, not a new button style.
   -------------------------------------------------------------------------- */
/* Every selector names the anchor on purpose. The body-link rule further up
   sets a dark ink colour and an underline, and a class-only button rule loses
   to it — which painted the dark button's label dark on dark. */
.${MARK}-actions{display:flex;flex-wrap:wrap;gap:12px;margin:28px 0 36px}
.${MARK} a.${MARK}-btn{display:inline-flex;align-items:center;
  justify-content:center;min-height:52px;padding:15px 30px;border-radius:999px;
  font-size:.9375rem;font-weight:600;letter-spacing:.01em;text-decoration:none;
  transition:background .16s ease,color .16s ease}
.${MARK} a.${MARK}-btn-primary{background:#E8C84B;color:#1B1B1B}
.${MARK} a.${MARK}-btn-primary:hover{background:#D9B72F;color:#000}
.${MARK} a.${MARK}-btn-secondary{background:#1B1B1B;color:#FDF9EE}
.${MARK} a.${MARK}-btn-secondary:hover{background:#000;color:#fff}

/* --------------------------------------------------------------------------
   Home page hero. The eyebrow carries the keyphrase above the client's own
   display line, so both survive; it must never run into it. Colours are
   inherited from the hero widget, because the hero sits on video and its text
   is white.
   -------------------------------------------------------------------------- */
.${MARK}-h1-eyebrow{display:block;font-family:"Inter","Inter Tight",system-ui,sans-serif;
  font-size:clamp(.7rem,1vw,.8125rem);letter-spacing:.22em;text-transform:uppercase;
  font-weight:600;color:#E8C84B;line-height:1.35;margin:0 0 20px}
.${MARK}-h1-main{display:block}
.${MARK}-hero-lede{color:inherit;font-size:clamp(1rem,1.3vw,1.1875rem);
  line-height:1.55;margin:0 0 10px;max-width:46ch}
.${MARK}-hero-sub{color:inherit;margin:0;opacity:.85}
/* Semantics only: this heading must look exactly like the text widget it
   replaced, so every inherited heading style is reset. */
.${MARK}-h2v{font:inherit;color:inherit;letter-spacing:inherit;
  line-height:inherit;text-transform:inherit;margin:0;padding:0;display:inline}

/* --------------------------------------------------------------------------
   Anything the client's own page owns still has to clear the fixed header
   when a cross-page link points at it.
   -------------------------------------------------------------------------- */
#calculator{scroll-margin-top:${HEADER_CLEARANCE}px}

@media (max-width:768px){
  .${MARK}{padding:64px 20px}
  .${MARK}-guide{padding:80px 20px 64px}
  .${MARK} h2{margin:44px 0 14px}
  .${MARK} p{font-size:1rem;line-height:1.7}
  .${MARK} p.${MARK}-guide-lede{font-size:1.125rem}
  .${MARK}-toc{padding:22px 20px;margin:36px 0 8px}
  .${MARK}-toc ul{columns:1}
  .${MARK}-toc li{margin-bottom:12px}
  .${MARK}-actions{flex-direction:column;align-items:stretch}
}

@media (prefers-reduced-motion:reduce){
  .${MARK}-q>summary::after,.${MARK}-btn{transition:none}
}

@media print{
  .${MARK}-q-body{display:block!important}
  .${MARK}-q>summary::after,.${MARK}-actions,.${MARK}-toc{display:none}
}
`;
